# Generated by Django 5.0.14 on 2026-07-05 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'chunk_embeddings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_uuid', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'column_embeddings',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnEmbeddingBGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_uuid', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'column_embeddings_bge',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnEmbeddingHybrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_uuid', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'column_embeddings_hybrid',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnEmbeddingLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_uuid', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'column_embeddings_lt',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphNodeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'graph_node_embeddings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelgtStructural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_uuid', models.UUIDField()),
                ('source_id', models.IntegerField()),
                ('tenant', models.TextField()),
            ],
            options={
                'db_table': 'relgt_structural',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('path', models.CharField(max_length=1024)),
                ('version', models.CharField(max_length=64)),
                ('kind', models.CharField(default='kuzu', max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('node_key', models.CharField(max_length=512)),
                ('node_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('edge_type', models.CharField(max_length=64)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='substrate.graphnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='substrate.graphnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('data_type', models.CharField(max_length=128)),
                ('is_pk', models.BooleanField(default=False)),
                ('is_fk', models.BooleanField(default=False)),
                ('semantic_type', models.CharField(blank=True, choices=[('MONETARY', 'Monetary'), ('TEMPORAL', 'Temporal'), ('CATEGORICAL', 'Categorical'), ('IDENTIFIER', 'Identifier'), ('FLAG', 'Flag'), ('TEXT', 'Text')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('review_flag', models.BooleanField(default=False)),
                ('excluded', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnValueSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('value', models.TextField()),
                ('freq', models.BigIntegerField(default=0)),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_samples', to='substrate.schemacolumn')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('distinct_count', models.BigIntegerField(blank=True, null=True)),
                ('top_n_json', models.JSONField(blank=True, default=list)),
                ('null_ratio', models.FloatField(blank=True, null=True)),
                ('min_value', models.TextField(blank=True)),
                ('max_value', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='substrate.schemacolumn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('display_column', models.CharField(blank=True, max_length=256)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='substrate.schematable'),
        ),
        migrations.CreateModel(
            name='FkEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('join_type', models.CharField(choices=[('INNER', 'Inner'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('FULL', 'Full')], default='INNER', max_length=8)),
                ('is_declared', models.BooleanField(default=True)),
                ('overlap_score', models.FloatField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
                ('from_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_out_cols', to='substrate.schemacolumn')),
                ('to_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_in_cols', to='substrate.schemacolumn')),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_out', to='substrate.schematable')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_in', to='substrate.schematable')),
            ],
        ),
        migrations.CreateModel(
            name='SemanticConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(choices=[('CONCEPT', 'Concept'), ('DIMENSION', 'Dimension'), ('METRIC', 'Metric')], max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('definition', models.TextField(blank=True)),
                ('mapping_json', models.JSONField(blank=True, default=dict)),
                ('manifest_version', models.CharField(blank=True, max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SemanticType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(choices=[('MONETARY', 'Monetary'), ('TEMPORAL', 'Temporal'), ('CATEGORICAL', 'Categorical'), ('IDENTIFIER', 'Identifier'), ('FLAG', 'Flag'), ('TEXT', 'Text')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('layer_hit', models.CharField(blank=True, max_length=64)),
                ('review_flag', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_types', to='substrate.schemacolumn')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('term', models.CharField(max_length=256)),
                ('synonym', models.CharField(max_length=256)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('nl_text', models.TextField()),
                ('ir_json', models.JSONField()),
                ('target_column', models.CharField(blank=True, max_length=256)),
                ('used_for_finetune', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('display_column', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='substrate.schematable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiedQueryCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('query_hash', models.CharField(max_length=64)),
                ('query_text', models.TextField()),
                ('verified_sql', models.TextField()),
                ('columns_json', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('term', models.CharField(max_length=256)),
                ('canonical', models.CharField(blank=True, max_length=256)),
                ('definition', models.TextField(blank=True)),
                ('provenance', models.CharField(choices=[('LLM', 'LLM'), ('RULE', 'Rule'), ('DECLARED', 'Declared')], default='LLM', max_length=16)),
                ('scope', models.CharField(blank=True, max_length=128)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'tenant', 'term'], name='substrate_g_source__468b87_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['source', 'tenant', 'node_type'], name='substrate_g_source__a58bef_idx'),
        ),
        migrations.AddIndex(
            model_name='columnvaluesample',
            index=models.Index(fields=['column'], name='substrate_c_column__04a098_idx'),
        ),
        migrations.AddIndex(
            model_name='schematable',
            index=models.Index(fields=['source', 'tenant', 'name'], name='substrate_s_source__a0875a_idx'),
        ),
        migrations.AddConstraint(
            model_name='schematable',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'name'), name='uq_schematable_natural'),
        ),
        migrations.AddIndex(
            model_name='schemacolumn',
            index=models.Index(fields=['source', 'tenant', 'table'], name='substrate_s_source__7e8c97_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemacolumn',
            constraint=models.UniqueConstraint(fields=('table', 'name'), name='uq_schemacolumn_natural'),
        ),
        migrations.AddIndex(
            model_name='fkedge',
            index=models.Index(fields=['source', 'tenant', 'from_table'], name='substrate_f_source__ea0e20_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticconcept',
            index=models.Index(fields=['source', 'tenant', 'kind', 'name'], name='substrate_s_source__2767a2_idx'),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=models.Index(fields=['source', 'tenant', 'term'], name='substrate_s_source__9ca417_idx'),
        ),
        migrations.AddIndex(
            model_name='verifiedquerycache',
            index=models.Index(fields=['source', 'tenant', 'query_hash'], name='substrate_v_source__98bd57_idx'),
        ),
        migrations.AddConstraint(
            model_name='verifiedquerycache',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'query_hash'), name='uq_verifiedcache_hash'),
        ),
    ]
