# Generated by Django 5.0.14 on 2026-07-05 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('substrate', '0002_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SmRetrievalDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('key', models.CharField(max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SmSynonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('phrase', models.CharField(max_length=512)),
                ('mappings', models.JSONField(default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SmTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SubstrateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('version', models.CharField(max_length=64)),
                ('sm_version', models.CharField(default='1.0', max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SmColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('key', models.CharField(max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'tenant', 'key'], name='substrate_s_source__86fe27_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='smcolumn',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'key'), name='uq_smcolumn'),
        ),
        migrations.AddConstraint(
            model_name='smconcept',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'name'), name='uq_smconcept'),
        ),
        migrations.AddConstraint(
            model_name='smretrievaldoc',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'key'), name='uq_smretrdoc'),
        ),
        migrations.AddIndex(
            model_name='smsynonym',
            index=models.Index(fields=['source', 'tenant', 'phrase'], name='substrate_s_source__844ead_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsynonym',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'phrase'), name='uq_smsynonym'),
        ),
        migrations.AddConstraint(
            model_name='smtable',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'name'), name='uq_smtable'),
        ),
        migrations.AddConstraint(
            model_name='substrateversion',
            constraint=models.UniqueConstraint(fields=('source', 'tenant'), name='uq_substrateversion_scope'),
        ),
    ]
