# Generated by Django 5.0.14 on 2026-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substrate', '0004_substrateversion_hnsw_ef_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphartifact',
            name='kind',
            field=models.CharField(default='relationship_graph', max_length=32),
        ),
    ]
