# Generated by Django 5.0.14 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_sourceitem_sourceitem_uq_sourceitem_natural'),
        ('substrate', '0008_drop_column_embeddings_bge'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verifiedquerycache',
            name='uq_verifiedcache_hash',
        ),
        migrations.RemoveIndex(
            model_name='verifiedquerycache',
            name='substrate_v_source__98bd57_idx',
        ),
        migrations.AddField(
            model_name='verifiedquerycache',
            name='substrate_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='verifiedquerycache',
            index=models.Index(fields=['source', 'tenant', 'query_hash', 'substrate_version'], name='substrate_v_source__f7a7ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='verifiedquerycache',
            constraint=models.UniqueConstraint(fields=('source', 'tenant', 'query_hash', 'substrate_version'), name='uq_verifiedcache_hash'),
        ),
    ]
