# =============================================================================
# ingestion/auto_finetune.py
# VEDA POC — Step 11: Automatic MiniLM Fine-Tuning
#
# Responsibility:
#   - Loads training pairs generated by synthetic_query_gen.py
#   - Fine-tunes MiniLM using Multiple Negatives Ranking Loss
#   - Saves client-specific checkpoint to AUTO_FINETUNE_CHECKPOINT_DIR
#   - relgt_encoder._get_minilm_model() loads the checkpoint on next run
#
# Option A design — encoder runs ONCE, after fine-tuning:
#   main.py calls run_auto_finetune() BEFORE run_relgt_encoder().
#   The fine-tuned model is saved to disk.
#   run_relgt_encoder() then loads it via _get_minilm_model() which
#   checks AUTO_FINETUNE_CHECKPOINT_DIR before falling back to base MiniLM.
#   Base MiniLM is never used in production when fine-tuning is enabled.
#
# Loss function — MultipleNegativesRankingLoss:
#   Given a batch of (query, column_sentence) positive pairs,
#   all other column sentences in the batch act as negatives.
#   This is in-batch negative sampling — no explicit negative labelling needed.
#   Effective for schema fine-tuning because columns from other tables
#   are natural negatives for any given query.
#
#   Mathematical objective:
#     For each query q_i with positive column sentence c_i:
#     Loss = -log(exp(sim(q_i, c_i) / τ) /
#                 Σ_j exp(sim(q_i, c_j) / τ))
#     where τ is a temperature parameter (learned or fixed)
#
# DB-agnostic design:
#   No DB calls at all. Reads training pairs from JSONL file only.
#   Works identically on PostgreSQL, MySQL, SQLite, Oracle, SQL Server.
#   The training data was generated from schema metadata — not query logs.
#
# Graceful degradation:
#   - sentence-transformers not installed → skip, log warning
#   - fewer than SYNTHETIC_MIN_PAIRS_FOR_FINETUNE pairs → skip
#   - Ollama generated only fallback pairs → still fine-tunes (lower quality)
#   - Training error → log, continue without fine-tuning
#   In all skip/error cases the base MiniLM is used — no pipeline failure.
# =============================================================================

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import json
import time
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

from ingestion.synthetic_query_gen import load_training_pairs, TrainingPair
from ingestion.semantic_type_inference import InferenceResult
from config import (
    MINILM_MODEL_NAME,
    MINILM_SENTENCE_TEMPLATE,
    MINILM_DEVICE,
    AUTO_FINETUNE_ENABLED,
    AUTO_FINETUNE_EPOCHS,
    AUTO_FINETUNE_BATCH_SIZE,
    AUTO_FINETUNE_WARMUP_STEPS,
    AUTO_FINETUNE_MAX_SEQ_LEN,
    AUTO_FINETUNE_CHECKPOINT_DIR,
    AUTO_FINETUNE_LR,
    SYNTHETIC_PAIRS_PATH,
    SYNTHETIC_MIN_PAIRS_FOR_FINETUNE,
    MINILM_FINETUNE_MODE,
)
from utils.logger import get_logger

logger = get_logger(__name__)


# =============================================================================
# sentence-transformers — graceful fallback
# =============================================================================

try:
    from sentence_transformers import SentenceTransformer, InputExample, losses
    from torch.utils.data import DataLoader
    ST_AVAILABLE = True
except ImportError:
    ST_AVAILABLE = False


# =============================================================================
# Output data structures
# =============================================================================

@dataclass
class FineTuneResult:
    """Top-level output of the fine-tuning step."""
    success:           bool
    checkpoint_path:   str
    pairs_used:        int
    epochs_completed:  int
    final_loss:        float
    duration_sec:      float
    skipped:           bool          # True if skipped gracefully
    skip_reason:       str           # why it was skipped (if skipped)
    stats:             dict = field(default_factory=dict)


# =============================================================================
# Column sentence builder
# Builds the "positive" side of each training pair.
# Must match the sentence format used by relgt_encoder._build_minilm_sentence()
# so embeddings are in the same vector space.
# =============================================================================

def _build_column_sentence(
    col_name:      str,
    table_name:    str,
    semantic_type: str,
) -> str:
    """
    Builds the canonical sentence for a column — matches relgt_encoder format.
    This is the POSITIVE sentence that the fine-tuner pairs with query text.
    """
    return MINILM_SENTENCE_TEMPLATE.format(
        col_name      = col_name,
        table_name    = table_name,
        semantic_type = semantic_type,
    )


# =============================================================================
# Training pair preparation
# =============================================================================

def _prepare_training_examples(
    pairs:             List[TrainingPair],
    inference_result:  InferenceResult,
) -> List["InputExample"]:
    """
    Converts TrainingPair objects into InputExample objects for sentence-transformers.

    Each InputExample is a (query_text, column_sentence) pair.
    The column_sentence format matches what relgt_encoder uses during ingestion
    so the fine-tuned model operates in the same embedding space.

    Parameters
    ----------
    pairs : List[TrainingPair]
        Training pairs from load_training_pairs().
    inference_result : InferenceResult
        Contains typed_columns with semantic_type info needed
        to build canonical column sentences.

    Returns
    -------
    List[InputExample]
    """
    # Build col_id → TypedColumn lookup for semantic type
    col_meta = {
        tc.col_id: tc
        for tc in inference_result.typed_columns
    }

    examples = []
    seen     = set()   # deduplicate (query, col_id) pairs

    for pair in pairs:
        key = (pair.query.lower().strip(), pair.col_id)
        if key in seen:
            continue
        seen.add(key)

        # Get semantic type for canonical sentence building
        tc = col_meta.get(pair.col_id)
        semantic_type = tc.semantic_type if tc else "FREE_TEXT"

        col_sentence = _build_column_sentence(
            col_name      = pair.col_name,
            table_name    = pair.table_name,
            semantic_type = semantic_type,
        )

        examples.append(InputExample(
            texts=[pair.query, col_sentence],
        ))

    return examples


# =============================================================================
# Core fine-tuning
# =============================================================================

def _run_finetune(
    model:    "SentenceTransformer",
    examples: List["InputExample"],
    verbose:  bool,
) -> Tuple[float, int]:
    """
    Runs the fine-tuning loop.

    Uses MultipleNegativesRankingLoss — in-batch negatives, no labels needed.
    Returns (final_loss_approx, epochs_completed).
    """
    if not examples:
        return 0.0, 0

    # Set max sequence length
    model.max_seq_length = AUTO_FINETUNE_MAX_SEQ_LEN

    # DataLoader — shuffle to ensure diverse in-batch negatives
    dataloader = DataLoader(
        examples,
        shuffle    = True,
        batch_size = AUTO_FINETUNE_BATCH_SIZE,
    )

    # Multiple Negatives Ranking Loss
    # scale parameter controls the temperature τ in the softmax
    train_loss = losses.MultipleNegativesRankingLoss(
        model = model,
        scale = 20.0,    # higher scale = sharper distribution = harder negatives
    )

    # Warmup steps across total training
    total_steps   = len(dataloader) * AUTO_FINETUNE_EPOCHS
    warmup_steps  = min(AUTO_FINETUNE_WARMUP_STEPS, total_steps // 4)

    if verbose:
        print(f"  Training examples  : {len(examples)}")
        print(f"  Batch size         : {AUTO_FINETUNE_BATCH_SIZE}")
        print(f"  Epochs             : {AUTO_FINETUNE_EPOCHS}")
        print(f"  Steps per epoch    : {len(dataloader)}")
        print(f"  Warmup steps       : {warmup_steps}")
        print(f"  Learning rate      : {AUTO_FINETUNE_LR}")
        print(f"  Device             : {MINILM_DEVICE}")
        print()

    # Block mlflow before fit — protobuf 4+ removed google.protobuf.service
    # which mlflow depends on. sys.modules[key]=None makes 'import key' raise
    # ImportError so sentence-transformers skips the MLflowCallback cleanly.
    import sys
    _blocked = [k for k in list(sys.modules) if k == "mlflow" or k.startswith("mlflow.")]
    _saved   = {k: sys.modules.pop(k) for k in _blocked}
    sys.modules["mlflow"] = None

    try:
        model.fit(
            train_objectives   = [(dataloader, train_loss)],
            epochs             = AUTO_FINETUNE_EPOCHS,
            warmup_steps       = warmup_steps,
            optimizer_params   = {"lr": AUTO_FINETUNE_LR},
            show_progress_bar  = verbose,
            use_amp            = False,
        )
    finally:
        del sys.modules["mlflow"]
        sys.modules.update(_saved)

    return 0.0, AUTO_FINETUNE_EPOCHS


# =============================================================================
# Glossary-based training pair generation
# =============================================================================

def _dicts_to_training_pairs(
    pairs_dicts:      list,
    inference_result: InferenceResult,
    source:           str,
) -> List[TrainingPair]:
    """Convert {query, col_id} dicts to TrainingPair objects using inference_result metadata."""
    col_meta = {tc.col_id: tc for tc in inference_result.typed_columns}
    result   = []
    for d in pairs_dicts:
        col_id = d.get("col_id", "")
        query  = d.get("query", "")
        if not col_id or not query:
            continue
        tc = col_meta.get(col_id)
        if tc is None:
            continue
        result.append(TrainingPair(
            query      = query,
            col_id     = col_id,
            col_name   = tc.col_name,
            table_name = tc.table_name,
            source     = source,
        ))
    return result


def _build_glossary_training_pairs(
    inference_result: InferenceResult,
    glossary:         dict,
    max_pairs:        int = 500,
) -> List[TrainingPair]:
    """
    Generate (query, col_id) training pairs from domain glossary.
    Processes glossary terms that match actual column names in the schema.
    """
    import random

    col_name_to_ids: dict = {}
    for tc in inference_result.typed_columns:
        name_lower = tc.col_name.lower()
        col_name_to_ids.setdefault(name_lower, []).append((tc.col_id, tc.col_name, tc.table_name))
        full_name = f"{tc.table_name.lower()}_{tc.col_name.lower()}"
        col_name_to_ids.setdefault(full_name, []).append((tc.col_id, tc.col_name, tc.table_name))

    QUERY_TEMPLATES = [
        "show all {term}",
        "find {term} from last month",
        "list {term} by status",
        "count {term} this week",
        "show {term} details",
        "get {term} records",
        "display {term} summary",
    ]

    pairs_dicts = []
    for term, col_names in glossary.items():
        if len(pairs_dicts) >= max_pairs:
            break
        matched = []
        for col_name in col_names:
            col_key = col_name.lower().replace(" ", "_")
            if col_key in col_name_to_ids:
                matched.extend(col_name_to_ids[col_key])
        if not matched:
            continue
        templates = random.sample(QUERY_TEMPLATES, min(3, len(QUERY_TEMPLATES)))
        for template in templates:
            query = template.format(term=term)
            for col_id, col_name, table_name in matched[:2]:
                pairs_dicts.append({"query": query, "col_id": col_id})

    return _dicts_to_training_pairs(pairs_dicts, inference_result, "glossary")


def _build_paraphrase_pairs(
    synthetic_pairs:  List[TrainingPair],
    glossary:         dict,
    inference_result: InferenceResult,
) -> List[TrainingPair]:
    """
    Generate domain-vocabulary paraphrases of synthetic pairs.
    Replaces col/table name tokens in query with glossary synonyms.
    """
    import re

    col_id_to_info = {
        tc.col_id: {"col_name": tc.col_name, "table_name": tc.table_name}
        for tc in inference_result.typed_columns
    }

    # Build reverse: col_name → glossary terms mapping to it
    col_to_terms: dict = {}
    for term, col_names in glossary.items():
        for col_name in col_names:
            col_lower = col_name.lower().replace(" ", "_")
            col_to_terms.setdefault(col_lower, []).append(term)

    pairs_dicts = []
    for pair in synthetic_pairs:
        info = col_id_to_info.get(pair.col_id)
        if not info:
            continue
        col_name = info["col_name"].lower()
        tbl_name = info["table_name"].lower()
        synonyms = list(set(
            col_to_terms.get(col_name, []) + col_to_terms.get(tbl_name, [])
        ))[:3]
        for syn in synonyms:
            new_query = pair.query.lower()
            for token in [col_name, tbl_name, col_name.replace("_", " ")]:
                if token in new_query and len(token) > 3:
                    new_query = new_query.replace(token, syn, 1)
                    break
            if new_query != pair.query.lower():
                pairs_dicts.append({"query": new_query, "col_id": pair.col_id})

    return _dicts_to_training_pairs(pairs_dicts, inference_result, "paraphrase")


# =============================================================================
# Shared fine-tune wrapper
# =============================================================================

def _run_finetune_for_model(
    model_name:     str,
    device:         str,
    checkpoint_dir: str,
    finetune_mode:  str,
    inference_result: InferenceResult,
    pairs_path:     str,
    verbose:        bool,
    label:          str,
) -> "FineTuneResult":
    """Shared fine-tune wrapper for MiniLM and BGE."""
    # Force CPU — MPS OOMs on Apple Silicon when BGE-large trains with
    # full gradients + optimizer states (~5GB) on top of inference allocations.
    import os as _os
    _os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
    device = "cpu"
    t0 = time.time()

    def _skip(reason):
        logger.info("%s fine-tune skipped: %s", label, reason)
        if verbose:
            print(f"  [{label}FineTune] Skipped: {reason}\n")
        return FineTuneResult(
            success=False, checkpoint_path=checkpoint_dir,
            pairs_used=0, epochs_completed=0, final_loss=0.0,
            duration_sec=round(time.time() - t0, 4),
            skipped=True, skip_reason=reason,
            stats={"skip_reason": reason},
        )

    if not AUTO_FINETUNE_ENABLED:
        return _skip("AUTO_FINETUNE_ENABLED=False")
    if not ST_AVAILABLE:
        return _skip("sentence-transformers not installed")

    # Load pairs
    synthetic_pairs = load_training_pairs(pairs_path)

    # Glossary
    glossary = {}
    if finetune_mode in ("glossary_only", "combined"):
        try:
            from ingestion.domain_glossary import load_glossary
            glossary = load_glossary()
        except Exception as _ge:
            logger.warning("Glossary load failed (%s)", _ge)

    # Mode branches
    if finetune_mode == "synthetic_only":
        pairs = synthetic_pairs
        if verbose: print(f"[{label}FineTune] Mode: synthetic_only — {len(pairs)} pairs")
    elif finetune_mode == "glossary_only":
        pairs = _build_glossary_training_pairs(inference_result, glossary)
        if verbose: print(f"[{label}FineTune] Mode: glossary_only — {len(pairs)} pairs")
    else:  # combined
        g_pairs = _build_glossary_training_pairs(inference_result, glossary)
        p_pairs = _build_paraphrase_pairs(synthetic_pairs, glossary, inference_result)
        seen, pairs = set(), []
        for p in synthetic_pairs + g_pairs + p_pairs:
            k = (p.query.lower().strip(), p.col_id)
            if k not in seen:
                seen.add(k); pairs.append(p)
        if verbose:
            print(f"[{label}FineTune] Mode: combined — {len(pairs)} pairs total")

    if len(pairs) < SYNTHETIC_MIN_PAIRS_FOR_FINETUNE:
        return _skip(f"Only {len(pairs)} pairs (min {SYNTHETIC_MIN_PAIRS_FOR_FINETUNE})")

    import gc, torch

    # Clear all model singletons so their tensors are freed before reloading for training
    try:
        import ingestion.biencoder as _bc
        if _bc._BIENCODER_MODEL_INSTANCE is not None:
            _bc._BIENCODER_MODEL_INSTANCE = None
    except Exception:
        pass

    try:
        import query.retrieval_v2 as _rv2
        _rv2._QUERY_ENCODER = None
    except Exception:
        pass

    try:
        import ingestion.relgt_encoder as _re
        _re._TFIDF_VECTORIZER = None
        _re._SVD_MODEL = None
    except Exception:
        pass

    gc.collect()
    gc.collect()
    if torch.backends.mps.is_available():
        torch.mps.empty_cache()
        torch.mps.synchronize()
    elif torch.cuda.is_available():
        torch.cuda.empty_cache()

    train_device = device if device else "cpu"

    # When training on CPU while MPS is available, sentence-transformers can still
    # route incidental ops to MPS (e.g. loss scale, tokeniser buffers). MPS is often
    # near its 6.77 GB limit from other in-process allocations (REG builder PyG graph,
    # cached tensors), so even an 8 MB touch crashes. Mask MPS for the duration of
    # model load + training, then restore it so the post-training reload uses MPS.
    _mps_patched = False
    _mps_mod_ref = None
    _mps_orig_available = _mps_orig_built = None
    if train_device == "cpu":
        try:
            import torch.backends.mps as _mps_mod_ref
            if _mps_mod_ref.is_available():
                _mps_orig_available      = _mps_mod_ref.is_available
                _mps_orig_built          = _mps_mod_ref.is_built
                _mps_mod_ref.is_available = lambda: False
                _mps_mod_ref.is_built     = lambda: False
                _mps_patched = True
        except Exception:
            pass

    print(f"  [{label}FineTune] Loading {model_name} on {train_device}...")
    try:
        model = SentenceTransformer(model_name, device=train_device)
        model = model.to(train_device)
        print(f"  [{label}FineTune] Model loaded ✓")
    except Exception as e:
        if _mps_patched:
            _mps_mod_ref.is_available = _mps_orig_available
            _mps_mod_ref.is_built     = _mps_orig_built
        return _skip(f"Failed to load {model_name}: {e}")

    try:
        examples = _prepare_training_examples(pairs, inference_result)
    except Exception as e:
        if _mps_patched:
            _mps_mod_ref.is_available = _mps_orig_available
            _mps_mod_ref.is_built     = _mps_orig_built
        return _skip(f"Failed to prepare examples: {e}")

    try:
        final_loss, epochs_done = _run_finetune(model, examples, verbose)
    except Exception as e:
        if _mps_patched:
            _mps_mod_ref.is_available = _mps_orig_available
            _mps_mod_ref.is_built     = _mps_orig_built
        return _skip(f"Fine-tuning failed: {e}")

    # Restore MPS so the post-training biencoder reload can use it for inference
    if _mps_patched:
        _mps_mod_ref.is_available = _mps_orig_available
        _mps_mod_ref.is_built     = _mps_orig_built

    try:
        os.makedirs(checkpoint_dir, exist_ok=True)
        model.save(checkpoint_dir)
        meta = {
            "base_model": model_name, "pairs_used": len(pairs),
            "epochs": epochs_done,
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "schema_tables": list({tc.table_name for tc in inference_result.typed_columns}),
        }
        with open(os.path.join(checkpoint_dir, "finetune_meta.json"), "w") as f:
            json.dump(meta, f, indent=2)
    except Exception as e:
        return _skip(f"Failed to save checkpoint: {e}")

    duration = round(time.time() - t0, 4)
    logger.info("%s fine-tune: pairs=%d epochs=%d checkpoint=%s", label, len(pairs), epochs_done, checkpoint_dir)

    return FineTuneResult(
        success=True, checkpoint_path=checkpoint_dir,
        pairs_used=len(pairs), epochs_completed=epochs_done,
        final_loss=final_loss, duration_sec=duration,
        skipped=False, skip_reason=None,
        stats={"pairs_used": len(pairs), "epochs": epochs_done},
    )


# =============================================================================
# Public entry point
# =============================================================================

def run_auto_finetune(
    inference_result: InferenceResult,
    pairs_path:       str  = SYNTHETIC_PAIRS_PATH,
    verbose:          bool = False,
) -> FineTuneResult:
    """
    Main entry point for Step 11.

    Loads training pairs, fine-tunes MiniLM, saves checkpoint.
    Called by main.py BEFORE run_relgt_encoder() (Option A design).

    Parameters
    ----------
    inference_result : InferenceResult
        Output of run_semantic_type_inference(). Used to build
        canonical column sentences for training pairs.
    pairs_path : str
        Path to JSONL file written by synthetic_query_gen.py.
    verbose : bool

    Returns
    -------
    FineTuneResult
        Always returns — skips gracefully on any failure.
    """
    from config import MINILM_MODEL_NAME, MINILM_DEVICE, MINILM_FINETUNE_MODE
    return _run_finetune_for_model(
        model_name=MINILM_MODEL_NAME, device=MINILM_DEVICE,
        checkpoint_dir=AUTO_FINETUNE_CHECKPOINT_DIR,
        finetune_mode=MINILM_FINETUNE_MODE,
        inference_result=inference_result, pairs_path=pairs_path,
        verbose=verbose, label="MiniLM",
    )


def run_bge_finetune(
    inference_result: InferenceResult,
    pairs_path:       str  = SYNTHETIC_PAIRS_PATH,
    verbose:          bool = False,
) -> FineTuneResult:
    """
    Fine-tunes BGE biencoder on client schema training pairs.
    Mirrors run_auto_finetune() but uses BIENCODER_MODEL and client_bge checkpoint.
    """
    from config import (BIENCODER_MODEL, BGE_FINETUNE_DEVICE,
                        BGE_FINETUNE_MODE, BGE_FINETUNE_BATCH_SIZE,
                        BGE_FINETUNE_EPOCHS, BGE_FINETUNE_MAX_SEQ_LEN)
    return _run_finetune_for_model(
        model_name      = BIENCODER_MODEL,
        device          = BGE_FINETUNE_DEVICE,
        checkpoint_dir  = "ingestion/client_bge",
        finetune_mode   = BGE_FINETUNE_MODE,
        inference_result= inference_result,
        pairs_path      = pairs_path,
        verbose         = verbose,
        label           = "BGE",
        batch_size      = BGE_FINETUNE_BATCH_SIZE,
        epochs          = BGE_FINETUNE_EPOCHS,
        max_seq_len     = BGE_FINETUNE_MAX_SEQ_LEN,
    )


def checkpoint_exists() -> bool:
    """
    Returns True if a valid fine-tuned checkpoint exists.
    Called by relgt_encoder._get_minilm_model() to decide which model to load.
    """
    meta_path = os.path.join(AUTO_FINETUNE_CHECKPOINT_DIR, "finetune_meta.json")
    model_path = os.path.join(AUTO_FINETUNE_CHECKPOINT_DIR, "pytorch_model.bin")
    # sentence-transformers saves either pytorch_model.bin or model.safetensors
    safetensors_path = os.path.join(AUTO_FINETUNE_CHECKPOINT_DIR, "model.safetensors")
    return (
        os.path.exists(meta_path) and
        (os.path.exists(model_path) or os.path.exists(safetensors_path))
    )


def get_checkpoint_meta() -> Optional[dict]:
    """Returns metadata from the saved checkpoint, or None if not present."""
    meta_path = os.path.join(AUTO_FINETUNE_CHECKPOINT_DIR, "finetune_meta.json")
    if not os.path.exists(meta_path):
        return None
    try:
        with open(meta_path) as f:
            return json.load(f)
    except Exception:
        return None


# =============================================================================
# Smoke test — python ingestion/auto_finetune.py
# =============================================================================

if __name__ == "__main__":
    from schema.simulate_schema import get_simulated_schema
    from ingestion.schema_scanner import run_schema_scanner
    from ingestion.semantic_type_inference import run_semantic_type_inference
    from ingestion.value_sampler import run_value_sampler
    from ingestion.synthetic_query_gen import run_synthetic_query_gen

    print("Running ingestion pipeline...")
    raw_schema       = get_simulated_schema()
    scan_result      = run_schema_scanner(raw_schema=raw_schema, verbose=False)
    inference_result = run_semantic_type_inference(
        scan_result=scan_result, verbose=False
    )
    run_value_sampler(inference_result=inference_result, verbose=False)

    inference_result._fk_edges = scan_result.fk_edges
    gen_result = run_synthetic_query_gen(
        inference_result=inference_result, verbose=False
    )

    print(f"Training pairs generated: {gen_result.total_pairs}")
    print(f"  (column={gen_result.column_pairs}, "
          f"fk={gen_result.fk_pairs}, "
          f"value={gen_result.value_pairs}, "
          f"fallback={gen_result.fallback_pairs})")
    print()

    print("Running auto fine-tuning...\n")
    result = run_auto_finetune(
        inference_result = inference_result,
        verbose          = True,
    )

    print("=" * 70)
    print("VEDA POC — Auto Fine-Tune Output")
    print("=" * 70)
    if result.skipped:
        print(f"  Skipped           : {result.skip_reason}")
    else:
        print(f"  Success           : {result.success}")
        print(f"  Pairs used        : {result.pairs_used}")
        print(f"  Epochs completed  : {result.epochs_completed}")
        print(f"  Checkpoint        : {result.checkpoint_path}")
        print(f"  Duration          : {result.duration_sec}s")
        print()
        meta = get_checkpoint_meta()
        if meta:
            print(f"  Checkpoint meta   :")
            for k, v in meta.items():
                print(f"    {k:<20} : {v}")