# Generated by Django 5.0.14 on 2026-07-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dialect', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server'), ('duckdb', 'DuckDB'), ('mongo', 'MongoDB'), ('es', 'Elasticsearch'), ('dynamo', 'DynamoDB')], max_length=20)),
                ('connector_type', models.CharField(max_length=64)),
                ('connection_secret_ref', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('ingesting', 'Ingesting'), ('ready', 'Ready'), ('failed', 'Failed')], default='registered', max_length=20)),
                ('ready', models.BooleanField(default=False)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ready', 'status'], name='sources_sou_ready_af86ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='SourceConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_min_size', models.PositiveIntegerField(default=1)),
                ('pool_max_size', models.PositiveIntegerField(default=5)),
                ('read_only_role', models.CharField(blank=True, max_length=128)),
                ('statement_timeout_ms', models.PositiveIntegerField(default=30000)),
                ('sensitive_pattern_overrides', models.JSONField(blank=True, default=list)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_profile', to='sources.source')),
            ],
        ),
    ]
