# Generated by Django 5.0.14 on 2026-07-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='db_user',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='source',
            name='dbname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='source',
            name='host',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='source',
            name='password_env',
            field=models.CharField(blank=True, help_text='env var holding the password, e.g. HOMZHUB_DB_PASSWORD', max_length=256),
        ),
        migrations.AddField(
            model_name='source',
            name='password_inline',
            field=models.CharField(blank=True, help_text='dev only; prefer password_env in prod', max_length=256),
        ),
        migrations.AddField(
            model_name='source',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='connection_secret_ref',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
