# Generated by Django 5.0.14 on 2026-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_source_document_datalake_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='Business description of what this source contains. Manual entry wins; auto-generated from observed metadata only when left blank.'),
        ),
        migrations.AddField(
            model_name='source',
            name='description_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='domain_tags',
            field=models.JSONField(blank=True, default=list, help_text='Business domain(s) this source covers, e.g. ["finance", "sales"]. Used for same-domain ambiguity resolution. Manual; never auto-inferred.'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_canonical',
            field=models.BooleanField(default=False),
        ),
    ]
