# Generated by Django 5.0.14 on 2026-08-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_source_description_source_description_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('table', 'Table'), ('dataset', 'Dataset'), ('document', 'Document'), ('collection', 'Collection')], max_length=20)),
                ('item_key', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('item_metadata', models.JSONField(blank=True, default=dict)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'item_type'], name='sources_sou_source__92074c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourceitem',
            constraint=models.UniqueConstraint(fields=('source', 'item_type', 'item_key'), name='uq_sourceitem_natural'),
        ),
    ]
