# Generated by Django 5.0.14 on 2026-07-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, max_length=128)),
                ('query_text', models.TextField()),
                ('route', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('no_table', 'No table'), ('clarify', 'Clarify'), ('refuse', 'Refuse'), ('ungrounded', 'Ungrounded'), ('qualifier_dropped', 'Qualifier dropped'), ('ir_mismatch', 'IR mismatch'), ('invalid', 'Invalid'), ('exec_error', 'Exec error')], max_length=32)),
                ('sub_results', models.JSONField(blank=True, default=list)),
                ('executed_sql', models.TextField(blank=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='query_logs', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='query_query_tenant_881f13_idx'), models.Index(fields=['created_at'], name='query_query_created_ac27df_idx')],
            },
        ),
    ]
