# Generated by Django 5.0.14 on 2026-07-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='sources.source'),
        ),
    ]
