# Generated by Django 5.0.14 on 2026-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_alter_querylog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='cache_hit',
            field=models.BooleanField(default=False),
        ),
    ]
