# Generated by Django 5.0.14 on 2026-09-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_querylog_token_usage'),
        ('sources', '0006_sourceitem_sourceitem_uq_sourceitem_natural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='querylog',
            name='participating_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querylog',
            name='warning_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', 'status'], name='querylog_user_status_idx'),
        ),
    ]
