# Generated by Django 5.0.14 on 2026-08-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0004_seed_permissions'),
        ('sources', '0004_source_document_datalake_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512, unique=True)),
                ('kind', models.CharField(max_length=20)),
                ('parent_path', models.CharField(blank=True, db_index=True, max_length=512)),
                ('substrate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_resources', to='sources.source')),
            ],
            options={
                'verbose_name': 'Catalog resource',
                'verbose_name_plural': 'Catalog resources',
                'ordering': ('path',),
                'indexes': [models.Index(fields=['source', 'is_active'], name='catalog_source_active_idx')],
            },
        ),
    ]
