# Generated by Django 5.0.14 on 2026-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0008_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
