# Generated by Django 5.0.14 on 2026-09-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0010_remove_permission_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_kind', models.CharField(blank=True, max_length=16)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=8)),
                ('reason_code', models.CharField(blank=True, choices=[('explicit_deny', 'Explicit deny grant'), ('no_grant', 'No matching grant'), ('undeclared', 'View declared no permission'), ('resolution_error', 'Permission resolution failed')], max_length=32)),
                ('mode', models.CharField(blank=True, max_length=8)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('view_name', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization decision',
                'verbose_name_plural': 'Authorization decisions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='authzdec_user_created_idx'), models.Index(fields=['decision', 'reason_code'], name='authzdec_dec_reason_idx')],
            },
        ),
    ]
